name: Currenncy Converter iOS Application

on:
    push:
         branches: [ main, dev ]
    pull_request:
        branches: [ main ]
  
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=16.3.1,name=iPhone 14 Pro Max']
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3.3.0
        with:
            ref: dev
      - name: Xcodebuild Action
        uses: sersoft-gmbh/xcodebuild-action@v2.0.1
        with:
          project: PayPay\ Demo.xcodeproj
          scheme: PayPay\ Demo
          destination: ${destination}
          action: build


#      - name: Unit Test
#        run: |
#          xcodebuild clean test -project PayPay\ Demo.xcodeproj -scheme PayPay\ DemoTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
#        env:
#          destination: ${{ matrix.destination }}
#      - name: UI Test
#        run: |
#          xcodebuild clean test -project PayPay\ Demo.xcodeproj -scheme PayPay\ DemoUITests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
#        env:
#          destination: ${{ matrix.destination }}

#      - name: Build
#        run: |
#          xcodebuild clean build -project PayPay\ Demo.xcodeproj -scheme PayPay\ Demo -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
          destination: ${{ matrix.destination }}
